version: "3"
networks:
    kafka_kafkanet:
        external: true

services:
    twitterapp:
        build: .
        hostname: twitterapp                                                         
        container_name: twitterapp
        volumes:
            - .:/app
        networks:                                                                                                                          
            - kafka_kafkanet
