version: "3"
networks:
    kafka_kafkanet:
        external: true
    rdbnet:

services:
    redditdb:  
        image: postgres     
        hostname: redditdb                                                    
        container_name: redditdb            
        environment:                                                            
            POSTGRES_USER: user                                                
            POSTGRES_PASSWORD: pass                                             
            POSTGRES_DB: myredb                                             
        volumes:                                                                
            - ./data:/var/lib/postgresql/data 
        networks:
            - rdbnet

    redditapp:
        build: .
        volumes:
            - .:/app
        depends_on:
            - redditdb
        networks:                                                               
            - rdbnet                                                           
            - kafka_kafkanet
